// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQSovU3ZdIcGtdP7rp8eGEgd8Bw2uPMgs',
    appId: '1:300730639558:web:75409d2472e3b9e97e23c7',
    messagingSenderId: '300730639558',
    projectId: 'proapp-cae83',
    authDomain: 'proapp-cae83.firebaseapp.com',
    storageBucket: 'proapp-cae83.firebasestorage.app',
    measurementId: 'G-W5XQR1NVG6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKBnRP3qkwAUEwWTgjdU4bNHmDIE5Hfqc',
    appId: '1:300730639558:android:23f55590aa10daa67e23c7',
    messagingSenderId: '300730639558',
    projectId: 'proapp-cae83',
    storageBucket: 'proapp-cae83.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlOkws5q0xzFfqIWHHxXlNI1oBHwfN_5Y',
    appId: '1:300730639558:ios:f6ce7e9996ba5e077e23c7',
    messagingSenderId: '300730639558',
    projectId: 'proapp-cae83',
    storageBucket: 'proapp-cae83.firebasestorage.app',
    iosBundleId: 'com.proservices.portal.proClientFlutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlOkws5q0xzFfqIWHHxXlNI1oBHwfN_5Y',
    appId: '1:300730639558:ios:f6ce7e9996ba5e077e23c7',
    messagingSenderId: '300730639558',
    projectId: 'proapp-cae83',
    storageBucket: 'proapp-cae83.firebasestorage.app',
    iosBundleId: 'com.proservices.portal.proClientFlutterapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQSovU3ZdIcGtdP7rp8eGEgd8Bw2uPMgs',
    appId: '1:300730639558:web:e283cca0cbe831d37e23c7',
    messagingSenderId: '300730639558',
    projectId: 'proapp-cae83',
    authDomain: 'proapp-cae83.firebaseapp.com',
    storageBucket: 'proapp-cae83.firebasestorage.app',
    measurementId: 'G-CRR6D3Z0FY',
  );
}
